---
version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: db_root
      MYSQL_DATABASE: db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_pass

  wordpress:
    depends_on:
      - mysql
    build:
      dockerfile: Dockerfile
    ports:
      - 80:80
    restart: always
    volumes:
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: db_user
      WORDPRESS_DB_PASSWORD: db_pass
      WORDPRESS_DB_NAME: db

volumes:
  mysql_data:
